print("     ++")
print("     ##")
print("    ~~~~")
print("  O      O ")
print(" (   **   ) ")
print("   @    @ ")
print("     ~~ ")
print("     **")
print(" ")
print("    {[   ]} ")
print("  {[       ]} ")
print(" {[ @     @ ]} ")
print(" {[    3    ]} ")
print("   {[     ]} ")
print("    {[   ]} ")
print(" ")
print("    ***** ")
print("  *       *")
print("   *     *")
print("     * *")
print("      *  ")